name = "Create Solo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46ca412fd7b534afce3033039455900e5a539b77c1aa75c79dcdc330d4b82869"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
