name = "Create Solo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0591932222db51df7a618a3c3be18e6338dea1637162dac02afacb9ae8dd20a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
